# Generated by Django 3.2.10 on 2022-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FregatMonitoringApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gases_consumptions_per_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.SmallIntegerField(blank=True, null=True)),
                ('consumption', models.FloatField(blank=True, null=True)),
                ('gasname', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
