# Generated by Django 3.2.10 on 2022-03-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FregatMonitoringApp', '0002_gases_consumptions_per_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gases_consumptions_per_day',
            options={'managed': False},
        ),
    ]
