# Generated by Django 3.2.10 on 2022-03-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FregatMonitoringApp', '0003_alter_gases_consumptions_per_day_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gases_consumptions_per_day',
            table='GasesConsumptionsPerDay',
        ),
    ]
