# Generated by Django 3.2.10 on 2022-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FregatMonitoringApp', '0004_alter_gases_consumptions_per_day_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtoplavka_status',
            fields=[
                ('furnace_no', models.SmallIntegerField(db_column='furnace_тo', primary_key=True, serialize=False)),
                ('auto_mode', models.BooleanField(blank=True, db_column='auto_mode', null=True)),
                ('melt_type', models.SmallIntegerField(blank=True, db_column='melt_type', null=True)),
                ('current_step', models.SmallIntegerField(blank=True, db_column='current_step', null=True)),
                ('current_substep', models.SmallIntegerField(blank=True, db_column='current_substep', null=True)),
                ('step_total_time', models.IntegerField(blank=True, db_column='step_time_preset', null=True)),
                ('step_time_remain', models.SmallIntegerField(blank=True, db_column='current_step_time_remain', null=True)),
                ('delta_t_curent', models.SmallIntegerField(blank=True, db_column='delta_t_current', null=True)),
                ('delta_t_stp', models.SmallIntegerField(blank=True, db_column='delta_t_stp', null=True)),
            ],
            options={
                'db_table': 'Avtoplavka_status',
                'managed': False,
            },
        ),
    ]
