# Generated by Django 3.2.10 on 2022-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FregatMonitoringApp', '0005_avtoplavka_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoplavka_log',
            fields=[
                ('log_id', models.IntegerField(db_column='log_id', primary_key=True, serialize=False)),
                ('furnace_no', models.SmallIntegerField(db_column='furnace_no')),
                ('melt_number', models.SmallIntegerField(db_column='melt_number')),
                ('melt_type', models.SmallIntegerField(blank=True, db_column='melt_type', null=True)),
                ('current_step', models.SmallIntegerField(blank=True, db_column='current_step', null=True)),
                ('current_substep', models.SmallIntegerField(blank=True, db_column='current_substep', null=True)),
                ('auto_mode', models.BooleanField(blank=True, db_column='auto_mode', null=True)),
                ('date_time', models.DateTimeField(blank=True, db_column='date_time', null=True)),
            ],
            options={
                'db_table': 'Autoplavka_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avtoplavka_setpoints',
            fields=[
                ('furnace_no', models.SmallIntegerField(db_column='furnace_no', primary_key=True, serialize=False)),
                ('auto_mode', models.BooleanField(blank=True, db_column='auto_mode', null=True)),
                ('melt_type', models.SmallIntegerField(blank=True, db_column='melt_type', null=True)),
                ('num_of_steps', models.SmallIntegerField(blank=True, db_column='num_of_steps', null=True)),
                ('num_of_substeps', models.SmallIntegerField(blank=True, db_column='num_of_substeps', null=True)),
                ('current_step_time', models.IntegerField(blank=True, db_column='current_step_time', null=True)),
                ('current_substep_time', models.SmallIntegerField(blank=True, db_column='current_substep_time', null=True)),
                ('delta_t_stp', models.SmallIntegerField(blank=True, db_column='delta_t_stp', null=True)),
                ('power_sp', models.SmallIntegerField(blank=True, db_column='power_sp', null=True)),
                ('rotation_sp', models.SmallIntegerField(blank=True, db_column='rotation_sp', null=True)),
                ('alpha_sp', models.SmallIntegerField(blank=True, db_column='alpha_sp', null=True)),
            ],
            options={
                'db_table': 'Avtoplavka_setpoints',
                'managed': False,
            },
        ),
    ]
