# Generated by Django 3.2.10 on 2023-02-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FregatMonitoringApp', '0006_autoplavka_log_avtoplavka_setpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarefaction_P2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_fur2_point1', models.IntegerField(db_column='rf_fur2_point1')),
                ('rf_fur2_point2', models.IntegerField(db_column='rf_fur2_point2')),
                ('rf_fur2_point3', models.IntegerField(db_column='rf_fur2_point3')),
                ('rf_fur2_point4', models.IntegerField(db_column='rf_fur2_point4')),
                ('rf_fur2_point5', models.IntegerField(db_column='rf_fur2_point5')),
                ('rf_fur2_point6', models.IntegerField(db_column='rf_fur2_point6')),
                ('rf_in_furnace', models.IntegerField(db_column='rf_in_furnace')),
                ('rf_in_ciclone_2pech', models.IntegerField(db_column='rf_in_ciclone_2pech')),
                ('timestamp', models.DateTimeField(db_column='timestamp')),
            ],
            options={
                'db_table': 'Rarefaction_P2',
                'managed': False,
            },
        ),
    ]
