# Generated by Django 3.2.10 on 2023-07-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FregatMonitoringApp', '0007_rarefaction_p2'),
    ]

    operations = [
        migrations.CreateModel(
            name='bottling',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('proddate', models.DateTimeField(blank=True, db_column='ProdDate', null=True)),
                ('grade', models.CharField(blank=True, db_column='Grade', max_length=50, null=True)),
                ('weight', models.CharField(blank=True, db_column='Weight', max_length=50, null=True)),
                ('lot', models.CharField(blank=True, db_column='Lot', max_length=50, null=True)),
                ('bundle', models.CharField(blank=True, db_column='Bundle', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Zebra',
                'managed': False,
            },
        )
    ]
