# Generated by Django 3.2.10 on 2023-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FregatMonitoringApp', '0009_furnace1_errors_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnace2_errors_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faults1', models.SmallIntegerField(blank=True, db_column='Faults1', null=True)),
                ('faults2', models.SmallIntegerField(blank=True, db_column='Faults2', null=True)),
                ('ng_press', models.SmallIntegerField(blank=True, db_column='NGPress', null=True)),
                ('o2_press', models.SmallIntegerField(blank=True, db_column='O2Press', null=True)),
                ('ng_flow', models.SmallIntegerField(blank=True, db_column='NGFlow', null=True)),
                ('o2_flow', models.SmallIntegerField(blank=True, db_column='O2Flow', null=True)),
                ('air_flow', models.SmallIntegerField(blank=True, db_column='AirFlow', null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
            ],
            options={
                'db_table': 'Furnace2_errors_log',
                'managed': False,
            },
        ),
    ]
